name: Send Email Report

on: 
  push:
  schedule:
    #- cron: "0 14 * * *"   # Runs every day at 14:00 UTC
    - cron: "*/30 * * * *"  # Runs every day 30 min
  workflow_dispatch:        # allows manual runs
#
jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.3"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run email script
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      run: python multi_rag_email_pipeline.py